/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Statistics } from "./Statistics";
import { StatisticsCountArgs } from "./StatisticsCountArgs";
import { StatisticsFindManyArgs } from "./StatisticsFindManyArgs";
import { StatisticsFindUniqueArgs } from "./StatisticsFindUniqueArgs";
import { CreateStatisticsArgs } from "./CreateStatisticsArgs";
import { UpdateStatisticsArgs } from "./UpdateStatisticsArgs";
import { DeleteStatisticsArgs } from "./DeleteStatisticsArgs";
import { Child } from "../../child/base/Child";
import { StatisticsService } from "../statistics.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Statistics)
export class StatisticsResolverBase {
  constructor(
    protected readonly service: StatisticsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Statistics",
    action: "read",
    possession: "any",
  })
  async _statisticsItemsMeta(
    @graphql.Args() args: StatisticsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Statistics])
  @nestAccessControl.UseRoles({
    resource: "Statistics",
    action: "read",
    possession: "any",
  })
  async statisticsItems(
    @graphql.Args() args: StatisticsFindManyArgs
  ): Promise<Statistics[]> {
    return this.service.statisticsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Statistics, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Statistics",
    action: "read",
    possession: "own",
  })
  async statistics(
    @graphql.Args() args: StatisticsFindUniqueArgs
  ): Promise<Statistics | null> {
    const result = await this.service.statistics(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Statistics)
  @nestAccessControl.UseRoles({
    resource: "Statistics",
    action: "create",
    possession: "any",
  })
  async createStatistics(
    @graphql.Args() args: CreateStatisticsArgs
  ): Promise<Statistics> {
    return await this.service.createStatistics({
      ...args,
      data: {
        ...args.data,

        child: args.data.child
          ? {
              connect: args.data.child,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Statistics)
  @nestAccessControl.UseRoles({
    resource: "Statistics",
    action: "update",
    possession: "any",
  })
  async updateStatistics(
    @graphql.Args() args: UpdateStatisticsArgs
  ): Promise<Statistics | null> {
    try {
      return await this.service.updateStatistics({
        ...args,
        data: {
          ...args.data,

          child: args.data.child
            ? {
                connect: args.data.child,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Statistics)
  @nestAccessControl.UseRoles({
    resource: "Statistics",
    action: "delete",
    possession: "any",
  })
  async deleteStatistics(
    @graphql.Args() args: DeleteStatisticsArgs
  ): Promise<Statistics | null> {
    try {
      return await this.service.deleteStatistics(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Child, {
    nullable: true,
    name: "child",
  })
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "read",
    possession: "any",
  })
  async getChild(@graphql.Parent() parent: Statistics): Promise<Child | null> {
    const result = await this.service.getChild(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
