/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { StatisticsService } from "../statistics.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StatisticsCreateInput } from "./StatisticsCreateInput";
import { Statistics } from "./Statistics";
import { StatisticsFindManyArgs } from "./StatisticsFindManyArgs";
import { StatisticsWhereUniqueInput } from "./StatisticsWhereUniqueInput";
import { StatisticsUpdateInput } from "./StatisticsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StatisticsControllerBase {
  constructor(
    protected readonly service: StatisticsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Statistics })
  @nestAccessControl.UseRoles({
    resource: "Statistics",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createStatistics(
    @common.Body() data: StatisticsCreateInput
  ): Promise<Statistics> {
    return await this.service.createStatistics({
      data: {
        ...data,

        child: data.child
          ? {
              connect: data.child,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        correctAnswers: true,
        wrongAnswers: true,
        totalCoins: true,

        child: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Statistics] })
  @ApiNestedQuery(StatisticsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Statistics",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async statisticsItems(@common.Req() request: Request): Promise<Statistics[]> {
    const args = plainToClass(StatisticsFindManyArgs, request.query);
    return this.service.statisticsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        correctAnswers: true,
        wrongAnswers: true,
        totalCoins: true,

        child: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Statistics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Statistics",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async statistics(
    @common.Param() params: StatisticsWhereUniqueInput
  ): Promise<Statistics | null> {
    const result = await this.service.statistics({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        correctAnswers: true,
        wrongAnswers: true,
        totalCoins: true,

        child: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Statistics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Statistics",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateStatistics(
    @common.Param() params: StatisticsWhereUniqueInput,
    @common.Body() data: StatisticsUpdateInput
  ): Promise<Statistics | null> {
    try {
      return await this.service.updateStatistics({
        where: params,
        data: {
          ...data,

          child: data.child
            ? {
                connect: data.child,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          correctAnswers: true,
          wrongAnswers: true,
          totalCoins: true,

          child: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Statistics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Statistics",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteStatistics(
    @common.Param() params: StatisticsWhereUniqueInput
  ): Promise<Statistics | null> {
    try {
      return await this.service.deleteStatistics({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          correctAnswers: true,
          wrongAnswers: true,
          totalCoins: true,

          child: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
