/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Child as PrismaChild,
  Contract as PrismaContract,
  Quiz as PrismaQuiz,
  Statistics as PrismaStatistics,
  Parent as PrismaParent,
} from "@prisma/client";

export class ChildServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ChildCountArgs, "select">): Promise<number> {
    return this.prisma.child.count(args);
  }

  async children(args: Prisma.ChildFindManyArgs): Promise<PrismaChild[]> {
    return this.prisma.child.findMany(args);
  }
  async child(args: Prisma.ChildFindUniqueArgs): Promise<PrismaChild | null> {
    return this.prisma.child.findUnique(args);
  }
  async createChild(args: Prisma.ChildCreateArgs): Promise<PrismaChild> {
    return this.prisma.child.create(args);
  }
  async updateChild(args: Prisma.ChildUpdateArgs): Promise<PrismaChild> {
    return this.prisma.child.update(args);
  }
  async deleteChild(args: Prisma.ChildDeleteArgs): Promise<PrismaChild> {
    return this.prisma.child.delete(args);
  }

  async findContracts(
    parentId: string,
    args: Prisma.ContractFindManyArgs
  ): Promise<PrismaContract[]> {
    return this.prisma.child
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .contracts(args);
  }

  async findQuizzes(
    parentId: string,
    args: Prisma.QuizFindManyArgs
  ): Promise<PrismaQuiz[]> {
    return this.prisma.child
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .quizzes(args);
  }

  async findStatisticsItems(
    parentId: string,
    args: Prisma.StatisticsFindManyArgs
  ): Promise<PrismaStatistics[]> {
    return this.prisma.child
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .statisticsItems(args);
  }

  async getParent(parentId: string): Promise<PrismaParent | null> {
    return this.prisma.child
      .findUnique({
        where: { id: parentId },
      })
      .parent();
  }
}
