/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ChildService } from "../child.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ChildCreateInput } from "./ChildCreateInput";
import { Child } from "./Child";
import { ChildFindManyArgs } from "./ChildFindManyArgs";
import { ChildWhereUniqueInput } from "./ChildWhereUniqueInput";
import { ChildUpdateInput } from "./ChildUpdateInput";
import { ContractFindManyArgs } from "../../contract/base/ContractFindManyArgs";
import { Contract } from "../../contract/base/Contract";
import { ContractWhereUniqueInput } from "../../contract/base/ContractWhereUniqueInput";
import { QuizFindManyArgs } from "../../quiz/base/QuizFindManyArgs";
import { Quiz } from "../../quiz/base/Quiz";
import { QuizWhereUniqueInput } from "../../quiz/base/QuizWhereUniqueInput";
import { StatisticsFindManyArgs } from "../../statistics/base/StatisticsFindManyArgs";
import { Statistics } from "../../statistics/base/Statistics";
import { StatisticsWhereUniqueInput } from "../../statistics/base/StatisticsWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ChildControllerBase {
  constructor(
    protected readonly service: ChildService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Child })
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createChild(@common.Body() data: ChildCreateInput): Promise<Child> {
    return await this.service.createChild({
      data: {
        ...data,

        parent: data.parent
          ? {
              connect: data.parent,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        classField: true,
        schoolNumber: true,

        parent: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Child] })
  @ApiNestedQuery(ChildFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async children(@common.Req() request: Request): Promise<Child[]> {
    const args = plainToClass(ChildFindManyArgs, request.query);
    return this.service.children({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        classField: true,
        schoolNumber: true,

        parent: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Child })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async child(
    @common.Param() params: ChildWhereUniqueInput
  ): Promise<Child | null> {
    const result = await this.service.child({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        classField: true,
        schoolNumber: true,

        parent: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Child })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateChild(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() data: ChildUpdateInput
  ): Promise<Child | null> {
    try {
      return await this.service.updateChild({
        where: params,
        data: {
          ...data,

          parent: data.parent
            ? {
                connect: data.parent,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          classField: true,
          schoolNumber: true,

          parent: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Child })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteChild(
    @common.Param() params: ChildWhereUniqueInput
  ): Promise<Child | null> {
    try {
      return await this.service.deleteChild({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          classField: true,
          schoolNumber: true,

          parent: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/contracts")
  @ApiNestedQuery(ContractFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Contract",
    action: "read",
    possession: "any",
  })
  async findContracts(
    @common.Req() request: Request,
    @common.Param() params: ChildWhereUniqueInput
  ): Promise<Contract[]> {
    const query = plainToClass(ContractFindManyArgs, request.query);
    const results = await this.service.findContracts(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        coinForCorrectAnswer: true,
        coinForWrongAnswer: true,
        timer: true,

        parent: {
          select: {
            id: true,
          },
        },

        child: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/contracts")
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  async connectContracts(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: ContractWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contracts: {
        connect: body,
      },
    };
    await this.service.updateChild({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/contracts")
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  async updateContracts(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: ContractWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contracts: {
        set: body,
      },
    };
    await this.service.updateChild({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/contracts")
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  async disconnectContracts(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: ContractWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contracts: {
        disconnect: body,
      },
    };
    await this.service.updateChild({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/quizzes")
  @ApiNestedQuery(QuizFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Quiz",
    action: "read",
    possession: "any",
  })
  async findQuizzes(
    @common.Req() request: Request,
    @common.Param() params: ChildWhereUniqueInput
  ): Promise<Quiz[]> {
    const query = plainToClass(QuizFindManyArgs, request.query);
    const results = await this.service.findQuizzes(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        subject: true,
        title: true,

        parent: {
          select: {
            id: true,
          },
        },

        contract: {
          select: {
            id: true,
          },
        },

        child: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/quizzes")
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  async connectQuizzes(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: QuizWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      quizzes: {
        connect: body,
      },
    };
    await this.service.updateChild({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/quizzes")
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  async updateQuizzes(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: QuizWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      quizzes: {
        set: body,
      },
    };
    await this.service.updateChild({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/quizzes")
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  async disconnectQuizzes(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: QuizWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      quizzes: {
        disconnect: body,
      },
    };
    await this.service.updateChild({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/statisticsItems")
  @ApiNestedQuery(StatisticsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Statistics",
    action: "read",
    possession: "any",
  })
  async findStatisticsItems(
    @common.Req() request: Request,
    @common.Param() params: ChildWhereUniqueInput
  ): Promise<Statistics[]> {
    const query = plainToClass(StatisticsFindManyArgs, request.query);
    const results = await this.service.findStatisticsItems(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        correctAnswers: true,
        wrongAnswers: true,
        totalCoins: true,

        child: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/statisticsItems")
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  async connectStatisticsItems(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: StatisticsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      statisticsItems: {
        connect: body,
      },
    };
    await this.service.updateChild({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/statisticsItems")
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  async updateStatisticsItems(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: StatisticsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      statisticsItems: {
        set: body,
      },
    };
    await this.service.updateChild({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/statisticsItems")
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "update",
    possession: "any",
  })
  async disconnectStatisticsItems(
    @common.Param() params: ChildWhereUniqueInput,
    @common.Body() body: StatisticsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      statisticsItems: {
        disconnect: body,
      },
    };
    await this.service.updateChild({
      where: params,
      data,
      select: { id: true },
    });
  }
}
