/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { ParentWhereUniqueInput } from "../../parent/base/ParentWhereUniqueInput";
import { Type } from "class-transformer";
import { ContractUpdateManyWithoutChildrenInput } from "./ContractUpdateManyWithoutChildrenInput";
import { QuizUpdateManyWithoutChildrenInput } from "./QuizUpdateManyWithoutChildrenInput";
import { StatisticsUpdateManyWithoutChildrenInput } from "./StatisticsUpdateManyWithoutChildrenInput";

@InputType()
class ChildUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  classField?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  schoolNumber?: string | null;

  @ApiProperty({
    required: false,
    type: () => ParentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ParentWhereUniqueInput)
  @IsOptional()
  @Field(() => ParentWhereUniqueInput, {
    nullable: true,
  })
  parent?: ParentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ContractUpdateManyWithoutChildrenInput,
  })
  @ValidateNested()
  @Type(() => ContractUpdateManyWithoutChildrenInput)
  @IsOptional()
  @Field(() => ContractUpdateManyWithoutChildrenInput, {
    nullable: true,
  })
  contracts?: ContractUpdateManyWithoutChildrenInput;

  @ApiProperty({
    required: false,
    type: () => QuizUpdateManyWithoutChildrenInput,
  })
  @ValidateNested()
  @Type(() => QuizUpdateManyWithoutChildrenInput)
  @IsOptional()
  @Field(() => QuizUpdateManyWithoutChildrenInput, {
    nullable: true,
  })
  quizzes?: QuizUpdateManyWithoutChildrenInput;

  @ApiProperty({
    required: false,
    type: () => StatisticsUpdateManyWithoutChildrenInput,
  })
  @ValidateNested()
  @Type(() => StatisticsUpdateManyWithoutChildrenInput)
  @IsOptional()
  @Field(() => StatisticsUpdateManyWithoutChildrenInput, {
    nullable: true,
  })
  statisticsItems?: StatisticsUpdateManyWithoutChildrenInput;
}

export { ChildUpdateInput as ChildUpdateInput };
