/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { ParentWhereUniqueInput } from "../../parent/base/ParentWhereUniqueInput";
import { Type } from "class-transformer";
import { ContractCreateNestedManyWithoutChildrenInput } from "./ContractCreateNestedManyWithoutChildrenInput";
import { QuizCreateNestedManyWithoutChildrenInput } from "./QuizCreateNestedManyWithoutChildrenInput";
import { StatisticsCreateNestedManyWithoutChildrenInput } from "./StatisticsCreateNestedManyWithoutChildrenInput";

@InputType()
class ChildCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  classField?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  schoolNumber?: string | null;

  @ApiProperty({
    required: false,
    type: () => ParentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ParentWhereUniqueInput)
  @IsOptional()
  @Field(() => ParentWhereUniqueInput, {
    nullable: true,
  })
  parent?: ParentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ContractCreateNestedManyWithoutChildrenInput,
  })
  @ValidateNested()
  @Type(() => ContractCreateNestedManyWithoutChildrenInput)
  @IsOptional()
  @Field(() => ContractCreateNestedManyWithoutChildrenInput, {
    nullable: true,
  })
  contracts?: ContractCreateNestedManyWithoutChildrenInput;

  @ApiProperty({
    required: false,
    type: () => QuizCreateNestedManyWithoutChildrenInput,
  })
  @ValidateNested()
  @Type(() => QuizCreateNestedManyWithoutChildrenInput)
  @IsOptional()
  @Field(() => QuizCreateNestedManyWithoutChildrenInput, {
    nullable: true,
  })
  quizzes?: QuizCreateNestedManyWithoutChildrenInput;

  @ApiProperty({
    required: false,
    type: () => StatisticsCreateNestedManyWithoutChildrenInput,
  })
  @ValidateNested()
  @Type(() => StatisticsCreateNestedManyWithoutChildrenInput)
  @IsOptional()
  @Field(() => StatisticsCreateNestedManyWithoutChildrenInput, {
    nullable: true,
  })
  statisticsItems?: StatisticsCreateNestedManyWithoutChildrenInput;
}

export { ChildCreateInput as ChildCreateInput };
