/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { ChildUpdateManyWithoutParentsInput } from "./ChildUpdateManyWithoutParentsInput";
import { Type } from "class-transformer";
import { ContractUpdateManyWithoutParentsInput } from "./ContractUpdateManyWithoutParentsInput";
import { QuizUpdateManyWithoutParentsInput } from "./QuizUpdateManyWithoutParentsInput";

@InputType()
class ParentUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string | null;

  @ApiProperty({
    required: false,
    type: () => ChildUpdateManyWithoutParentsInput,
  })
  @ValidateNested()
  @Type(() => ChildUpdateManyWithoutParentsInput)
  @IsOptional()
  @Field(() => ChildUpdateManyWithoutParentsInput, {
    nullable: true,
  })
  children?: ChildUpdateManyWithoutParentsInput;

  @ApiProperty({
    required: false,
    type: () => ContractUpdateManyWithoutParentsInput,
  })
  @ValidateNested()
  @Type(() => ContractUpdateManyWithoutParentsInput)
  @IsOptional()
  @Field(() => ContractUpdateManyWithoutParentsInput, {
    nullable: true,
  })
  contracts?: ContractUpdateManyWithoutParentsInput;

  @ApiProperty({
    required: false,
    type: () => QuizUpdateManyWithoutParentsInput,
  })
  @ValidateNested()
  @Type(() => QuizUpdateManyWithoutParentsInput)
  @IsOptional()
  @Field(() => QuizUpdateManyWithoutParentsInput, {
    nullable: true,
  })
  quizzes?: QuizUpdateManyWithoutParentsInput;
}

export { ParentUpdateInput as ParentUpdateInput };
