/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ParentService } from "../parent.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ParentCreateInput } from "./ParentCreateInput";
import { Parent } from "./Parent";
import { ParentFindManyArgs } from "./ParentFindManyArgs";
import { ParentWhereUniqueInput } from "./ParentWhereUniqueInput";
import { ParentUpdateInput } from "./ParentUpdateInput";
import { ChildFindManyArgs } from "../../child/base/ChildFindManyArgs";
import { Child } from "../../child/base/Child";
import { ChildWhereUniqueInput } from "../../child/base/ChildWhereUniqueInput";
import { ContractFindManyArgs } from "../../contract/base/ContractFindManyArgs";
import { Contract } from "../../contract/base/Contract";
import { ContractWhereUniqueInput } from "../../contract/base/ContractWhereUniqueInput";
import { QuizFindManyArgs } from "../../quiz/base/QuizFindManyArgs";
import { Quiz } from "../../quiz/base/Quiz";
import { QuizWhereUniqueInput } from "../../quiz/base/QuizWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ParentControllerBase {
  constructor(
    protected readonly service: ParentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Parent })
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createParent(@common.Body() data: ParentCreateInput): Promise<Parent> {
    return await this.service.createParent({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        password: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Parent] })
  @ApiNestedQuery(ParentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async parents(@common.Req() request: Request): Promise<Parent[]> {
    const args = plainToClass(ParentFindManyArgs, request.query);
    return this.service.parents({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        password: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Parent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async parent(
    @common.Param() params: ParentWhereUniqueInput
  ): Promise<Parent | null> {
    const result = await this.service.parent({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Parent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateParent(
    @common.Param() params: ParentWhereUniqueInput,
    @common.Body() data: ParentUpdateInput
  ): Promise<Parent | null> {
    try {
      return await this.service.updateParent({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Parent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteParent(
    @common.Param() params: ParentWhereUniqueInput
  ): Promise<Parent | null> {
    try {
      return await this.service.deleteParent({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/children")
  @ApiNestedQuery(ChildFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Child",
    action: "read",
    possession: "any",
  })
  async findChildren(
    @common.Req() request: Request,
    @common.Param() params: ParentWhereUniqueInput
  ): Promise<Child[]> {
    const query = plainToClass(ChildFindManyArgs, request.query);
    const results = await this.service.findChildren(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        classField: true,
        schoolNumber: true,

        parent: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/children")
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "update",
    possession: "any",
  })
  async connectChildren(
    @common.Param() params: ParentWhereUniqueInput,
    @common.Body() body: ChildWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      children: {
        connect: body,
      },
    };
    await this.service.updateParent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/children")
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "update",
    possession: "any",
  })
  async updateChildren(
    @common.Param() params: ParentWhereUniqueInput,
    @common.Body() body: ChildWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      children: {
        set: body,
      },
    };
    await this.service.updateParent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/children")
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "update",
    possession: "any",
  })
  async disconnectChildren(
    @common.Param() params: ParentWhereUniqueInput,
    @common.Body() body: ChildWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      children: {
        disconnect: body,
      },
    };
    await this.service.updateParent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/contracts")
  @ApiNestedQuery(ContractFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Contract",
    action: "read",
    possession: "any",
  })
  async findContracts(
    @common.Req() request: Request,
    @common.Param() params: ParentWhereUniqueInput
  ): Promise<Contract[]> {
    const query = plainToClass(ContractFindManyArgs, request.query);
    const results = await this.service.findContracts(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        coinForCorrectAnswer: true,
        coinForWrongAnswer: true,
        timer: true,

        parent: {
          select: {
            id: true,
          },
        },

        child: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/contracts")
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "update",
    possession: "any",
  })
  async connectContracts(
    @common.Param() params: ParentWhereUniqueInput,
    @common.Body() body: ContractWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contracts: {
        connect: body,
      },
    };
    await this.service.updateParent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/contracts")
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "update",
    possession: "any",
  })
  async updateContracts(
    @common.Param() params: ParentWhereUniqueInput,
    @common.Body() body: ContractWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contracts: {
        set: body,
      },
    };
    await this.service.updateParent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/contracts")
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "update",
    possession: "any",
  })
  async disconnectContracts(
    @common.Param() params: ParentWhereUniqueInput,
    @common.Body() body: ContractWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contracts: {
        disconnect: body,
      },
    };
    await this.service.updateParent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/quizzes")
  @ApiNestedQuery(QuizFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Quiz",
    action: "read",
    possession: "any",
  })
  async findQuizzes(
    @common.Req() request: Request,
    @common.Param() params: ParentWhereUniqueInput
  ): Promise<Quiz[]> {
    const query = plainToClass(QuizFindManyArgs, request.query);
    const results = await this.service.findQuizzes(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        subject: true,
        title: true,

        parent: {
          select: {
            id: true,
          },
        },

        contract: {
          select: {
            id: true,
          },
        },

        child: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/quizzes")
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "update",
    possession: "any",
  })
  async connectQuizzes(
    @common.Param() params: ParentWhereUniqueInput,
    @common.Body() body: QuizWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      quizzes: {
        connect: body,
      },
    };
    await this.service.updateParent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/quizzes")
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "update",
    possession: "any",
  })
  async updateQuizzes(
    @common.Param() params: ParentWhereUniqueInput,
    @common.Body() body: QuizWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      quizzes: {
        set: body,
      },
    };
    await this.service.updateParent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/quizzes")
  @nestAccessControl.UseRoles({
    resource: "Parent",
    action: "update",
    possession: "any",
  })
  async disconnectQuizzes(
    @common.Param() params: ParentWhereUniqueInput,
    @common.Body() body: QuizWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      quizzes: {
        disconnect: body,
      },
    };
    await this.service.updateParent({
      where: params,
      data,
      select: { id: true },
    });
  }
}
